<?php
	return array(
			"ALPU" => "ALP-H",
			"Urea/Bun" => "Urea",
			"Glu" => "Glucose",
			"Bilirubin Total(BIT))" => "Bilirubin Total(BIT)",
			"Epithelial cell" => "Epithelial cells",
			"Cast" => "Casts",
			"Yeast cell" => "Yeast cells",
			"HepB" => "Hepatitis B",
			"ALT" => "ALT-H",
			"AST" => "AST-H",
			"ALP" => "ALP-H",
			"ALB" => "ALB-H",
			"TBIL-VOX" => "Bilirubin Total(TBIL-VOX)",
			"DBIL-VOX" => "Bilirubin Direct(DBIL-VOX)",
			"HDL-C"  => "HDL Direct (HDL-C)",
			"LDL-C" => "LDL Direct (LDL-C)",
			"r-GT" => "GGT/r-GT",
			"DBIL-DSA" => "DBIL-DSA-H",
			"TBIL-DSA" => "TBIL-DSA-H",
			"TP" => "TP-H",
			"Results" => "Blood film",
			"GGT" => "GGT/r-GT",
			"Sickling Screen By Sodium Metabiosulphate Method" => "Sickling Screen",
			"P_LCR" => "P-LCR",
			"Total Cholesterol(CHOL)" => "Cholesterol(CHOL)",
			"GLU-O" => "GLU-O-H",
			"TG" => "TG-H",
			"Sickle" => "Sickling Screen",
			"Cholestero l(CHOL)" => "Cholesterol(CHOL)",
			"Cryptococcal Antigen" => "CrAg",
			"Cryptococcal Antig" => "CrAg",
			"Cryptococcal Anti" => "CrAg",
			"RIF RESISTANT" => "RIF Resistance",
			"Total Protien" => "Total Proteins"
        );
?>